"
CLASS zbp_nept_qz_i_quiz_u DEFINITION
  PUBLIC
  ABSTRACT
  FINAL
  FOR BEHAVIOR OF znept_qz_i_quiz_u.

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.

CLASS zbp_nept_qz_i_quiz_u IMPLEMENTATION.
ENDCLASS.
